#!/usr/bin/env bash

set -eu

case "$*" in
  '-t LABEL=INFRA-RECOVERY -o device')
    printf '%s\n' '/dev/mock-infra-recovery'
    ;;
  '-s TYPE -o value -- /dev/mock-infra-recovery')
    printf '%s\n' 'ext4'
    ;;
  '-s UUID -o value -- /dev/mock-infra-recovery')
    printf '%s\n' 'TEST-UUID'
    ;;
  *)
    exit 2
    ;;
esac
