#!/usr/bin/env bash

set -eu

query_kind=""
query_value=""
output_field=""

while (( $# > 0 )); do
  case "$1" in
    -S|-M|-T)
      query_kind="$1"
      query_value="$2"
      shift 2
      ;;
    -o)
      output_field="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

case "${query_kind}:${output_field}" in
  '-S:TARGET')
    if [[ -f "$NOVA_MOCK_MOUNT_STATE" ]]; then
      IFS= read -r mountpoint < "$NOVA_MOCK_MOUNT_STATE"
      printf '%s\n' "$mountpoint"
    else
      exit 1
    fi
    ;;
  '-M:UUID'|'-T:UUID')
    printf '%s\n' 'TEST-UUID'
    ;;
  '-M:FSTYPE')
    printf '%s\n' 'ext4'
    ;;
  '-M:OPTIONS')
    printf '%s\n' 'ro,nosuid,nodev,noexec'
    ;;
  *)
    exit 1
    ;;
esac
