#!/usr/bin/env bash

set -eu

database="${1:-}"
key="${2:-}"
case "${database}:${key}" in
  passwd:admin)
    if [[ "${NOVA_PHASE3_TEST_ADMIN_PRESENT:-1}" == "0" ]]; then
      exit 2
    fi
    printf '%s\n' 'admin:x:1000:1000:Administrator:/home/admin:/bin/bash'
    ;;
  group:docker)
    grep -Fqx -- 'docker-ce' "$NOVA_PHASE3_TEST_PACKAGE_STATE" 2>/dev/null || exit 2
    printf '%s\n' 'docker:x:995:'
    ;;
  *)
    exit 2
    ;;
esac
