server:
    chroot: ""
    verbosity: 1
    interface: 0.0.0.0
    port: 5335
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    module-config: "validator iterator"
    root-hints: "/var/lib/unbound/root.hints"

    access-control: 127.0.0.0/8 allow
    access-control: 10.0.0.0/8 allow
    access-control: 192.168.0.0/16 allow
    access-control: 10.8.0.0/16 allow

    hide-identity: yes
    hide-version: yes
    harden-algo-downgrade: yes
    harden-referral-path: yes
    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-below-nxdomain: yes
    qname-minimisation: yes
    aggressive-nsec: yes

    cache-min-ttl: 3600
    cache-max-ttl: 86400
    prefetch: yes
    prefetch-key: yes
    serve-expired: yes
    serve-expired-ttl: 172800
    serve-expired-client-timeout: 1800
    serve-expired-reply-ttl: 30

    num-threads: 1
    msg-cache-size: 128m
    rrset-cache-size: 256m
    so-rcvbuf: 8m
    so-sndbuf: 8m
    num-queries-per-thread: 2048
    outgoing-range: 2048
    jostle-timeout: 200
    edns-buffer-size: 1232

forward-zone:
    name: "."
    forward-addr: 9.9.9.9
    forward-addr: 149.112.112.112
    forward-first: yes
