services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    restart: unless-stopped
    entrypoint:
      - /bin/sh
      - -c
      - |
        update-alternatives --install /usr/sbin/iptables iptables /usr/sbin/iptables-nft 20 \
          --slave /usr/sbin/iptables-restore iptables-restore /usr/sbin/iptables-nft-restore \
          --slave /usr/sbin/iptables-save iptables-save /usr/sbin/iptables-nft-save
        update-alternatives --install /usr/sbin/ip6tables ip6tables /usr/sbin/ip6tables-nft 20 \
          --slave /usr/sbin/ip6tables-restore ip6tables-restore /usr/sbin/ip6tables-nft-restore \
          --slave /usr/sbin/ip6tables-save ip6tables-save /usr/sbin/ip6tables-nft-save
        exec docker-entrypoint.sh "$@"
      - --
    command: ["/usr/bin/dumb-init", "node", "server/index.mjs"]
    environment:
      PORT: "51821"
      HOST: "0.0.0.0"
      INSECURE: "true"
      DISABLE_IPV6: "true"
    volumes:
      - "/opt/wg-easy/data:/etc/wireguard"
      - "/lib/modules:/lib/modules:ro"
    ports:
      - "0.0.0.0:51824:51824/udp"
      - "0.0.0.0:51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv4.conf.all.src_valid_mark: "1"
      net.ipv6.conf.all.disable_ipv6: "1"
